baseURL: "https://katyayani.vercel.app"
languageCode: "en-us"
title: "Katyayani | Portfolio"
theme: master


Paginate: 3
disqusShortname: Katya
googleAnalytics: G-DWJJVE27WD
canonifyURLs:  true


markup:
 goldmark:
   renderer:
     unsafe: true


#Menus:
 #main:
   #- identifier: blog
     #name: Blog
     #title: Blog posts
     #url: /blogs
     #weight: 1


   #Dropdown menu
   #- identifier: dropdown
     #title: Example dropdown menu
     #name: Dropdown
     #weight: 2
   #- identifier: dropdown1
     #title: example dropdown 1
     #name: example 1
     #url: /#
     #parent: dropdown
     #weight: 1
   #- identifier: dropdown2
     #title: example dropdown 2
     #name: example 2
     #url: /#
     #parent: dropdown
     #weight: 2


params:
 #title: "Hugo Profile"
 #description: Text about my cool site
 # staticPath: ""  # The path to serve the static files from
 favicon: "/fav.png"


 theme:
   disableThemeToggle: false
   defaultTheme: "light" # dark
   color: 
       secondaryBackgroundColor: "Blue"
   #darkmode:
       #secondaryBackgroundColor: "Blue"


 # font:
 #   fontSize: 1.5rem # default: 1rem
 #   fontWeight: 500 # default: 400
 #   lineHeight: 1 # default: 1.5
 #   textAlign: right # default: left


 # color preference
 # color:
 #     textColor: "black"
 #     secondaryTextColor:
 #     backgroundColor:
 #     secondaryBackgroundColor:
 #     primaryColor:
 #     secondaryColor:


 #   darkmode:
 #     textColor:
 #     secondaryTextColor:
 #     backgroundColor:
 #     secondaryBackgroundColor:
 #     primaryColor:
 #     secondaryColor:


 # If you want to customize the menu, you can change it here
 navbar:
     position: absolute
 #   align: mx-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
 #   brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
 #   brandName: "Profile" # Brand name for the brand | default is the title variable


 #   menus:
 #     disableAbout: true
 #     disableExperience: true
 #     disableEducation: true
 #     disableProjects: true
 #     disableAchievements: true
 #     disableContact: true


 # Hero
 hero:
   enable: true
   intro: "Hi there! I'm"
   title: "Katyayani Jandhyala"
   # subtitle: Data Scientist | MSBA @ UIUC | Ex-BCG | IIIT-B | VIT
   content: "I'm a passionate business analytics enthusiast on a quest to explore uncharted territories in data science and deliver value-driven solutions across diverse domains. I live in Urbana Champaign, Illinos"
   image: "images/katya.png"
   button:
     background - color:
     enable: true
     name: "Resume"
     #url: "https://drive.google.com/file/d/1O_tSQAoBPswfecgqsQ5sa8s5BwnBgWss/view?usp=sharing"
     url: "https://drive.google.com/file/d/1UWivEmD7duT4hJR5Ki-SZbNo4dOUDXIy/view?usp=sharing"
   socialLinks:
     fontAwesomeIcons:
       - icon: fab fa-github
         url: https://github.com/Katyayani09
       - icon: fab fa-linkedin
         url: https://www.linkedin.com/in/katyayanijs/
      # - icon: fab fa-instagram
       #  url: https://www.instagram.com/cholechaawal/
     #customIcons:
       #- icon: /fav.png
       #  url: "https://example.com"


 # About
 about:
   enable: true
   title: "I'm open to work immediately."
   content: |-
     I am currently working as a Teaching Assisstant at University of Illinois Urbana-Champaign, US
    
     I am proficient in Python, R and SQL. My field of Interest's are building efficient ETL pipelines and also in areas related to Data and Business Analysis, Machine Learning and Cloud Computing.
     I have also extended my passion for developing smart data products using Python and Modern Big Data Frameworks like Hadoop, Hive and SAS, and deployed them on cloud platforms like AWS and GCP.
     Furthermore, I have also generated visualizations of my analyzed data on platforms like Tableau.


   skills:
     enable: true
     title: "Please find below my Tech Stack and Skills:"
     items:
       - "Languages: Python, R, SQL"
       - "Containerization & Orchestration: Docker, Kubernetes"
       - "Business Intelligence Tools: Microsoft Excel, Google Sheets, Tableau, Microsoft PowerBI, SAS"
       - "Big Data Technologies: Apache Hadoop, Apache hive, Apache Airflow, Apache Spark, Apache Nifi"
       - "Soft Skills: Mentorship, Multi-Cultural Fluency, Team Player, Leadership"
       - "Version Control Tools: Git, Github"
       - "Database Technologies: Oracle, PL/SQL, PostGresSQL, Redis"
       - "Cloud Technologies: AWS, Azure, Google Cloud Platform"


 # Education
 experience:
   enable: true
   items:     
     - job: "MS, Business Analytics"
       company: "University of Illinois Urbana-Champaign"
       companyUrl: "https://giesbusiness.illinois.edu/"
       date: "Aug 2022 - May 2023"
       featuredLink:
         enable: false
         url: "https://giesbusiness.illinois.edu/"
       content: |-
          - currently a Teaching Assistant for Big Data at the Gies College of Business - University of Illinois Urbana-Champaign
          - Course Work: Revenue Management, Business Practicum, Enterprise Database Management, Big Data Infrastructures, Supply Chain Analytics, Data Science and Analytics, Project Management, Marketing Analytics, Data Storytelling, Big Data Analytics in Finance.
    
     - job: "PG Diploma, Data Science with specialization in Deep Learning"
       company: "International Institute of Information Technology"
       companyUrl: "https://www.iiitb.ac.in/"
       date: "Mar 2020 - Apr 2021"
       featuredLink:
         enable: false
         url: "https://www.iiitb.ac.in/"
       content: |-
          - Pursued Data Science with concentration Deep Learning
          - Course Work: Discriminative, Generative and Hybrid Learnings

     - job: "BTech, Computer Science and Engineering"
       company: "VIT University"
       companyUrl: "https://vit.ac.in/"
       date: "Jul 2015 - Jul 2019"
       featuredLink:
         enable: false
         url: "https://vit.ac.in/"
       content: |-
          - Graduated from Computer Science and Engineering (SCOPE) at VIT University, Vellore with a CGPA of 3.4. During my studies
          - Course Work: Machine Learning, Artificial Intelligence, Data Mining, Cyber Security, Network and Communication, Image Processing, Content Based Image and Video Retrieval, Parallel and Distributed Computing,Green and Energy Aware Computing, Theory of Computation, Object Oriented Programming in Python, Software Engineering, Sensors and Instrumentation, Internet of Things, Database Management Systems, Mass Media and Society, Principles of Marketing, Lean-Startup Management, Calculus, Statistics and Probability, and Linear Algebra.
          - Board Member at IEEE-TEMS Chapter 
          - Innovations Intern at TIFAC-CORE in Automotive Infotronics 
          - Qualified for Silver & Bronze Echelon at Hack4Cause - a 24 hours Hackathon at the 16th International Conference on Science,Engineering and Technology (ICSET 2018)


 # Experience
 education:
   enable: true
   # index: true
   items:
     - title: "Project Intern, Business Practicum"
       school:
         name: "Wolters Kluwer"
         url: "https://www.wolterskluwer.com/"
       date: "Jan 2023 - May 2023"
       content: |-
           Champaign, Illinois, United States
           
           - Performed customer segmentation of large data sets using entity resolution recommendations system for anomaly detection, optimizing accuracy by deep learning with Pytorch, Keras and TensorFlow
           - Implemented A/B optimization to compare parallelized processing reducing processing time from 2 hours to 50 minutes
           - Leveraged advanced topic modeling techniques such as Latent Dirichlet Allocation (LDA) and guided LDA to effectively analyze copious amounts of ticketing data from multiple global regions
           - Employed unsupervised machine learning algorithms to accurately classify tickets into their respective issue categories, streamlining the issue resolution process for faster turnaround times

     - title: "Senior Data Analyst"
       school:
         name: "Ganit Inc"
         url: "https://www.ganitinc.com/"
       date: "Mar 2020 - Aug 2021"
       content: |-
          Chennai, Tamil Nadu, India

            - Developed and deployed Tableau dashboards to track 30+ KPIs for hypermarkets, providing a data-driven platform for business stakeholders and, also, reduced weekly man hours by 66.7%
            - Led the migration from SQL Server to Redshift using Amazon Athena & S3, resulting in an annual cost savings of $14,000& increased performance of 23%
            - Spearheaded the design and implementation of a Jenkins-based CI/CD pipeline for a prominent retail e-commerce client. This innovative solution seamlessly integrated Docker and Kubernetes, delivering remarkable results—a remarkable 40% reduction in deployment time while fortifying security through robust Identity and Access Management (IAM) policies
            - Led a data integration initiative, extracting and standardizing data from 40+ sources into a unified format via the creation of 5 ETL packages using Oracle PL/SQL. Further, developed database applications, using Packages, Functions, Procedures, Triggers in PL/SQL, with a strong background in troubleshooting, and performance tuning.
            - Developed data pipelines through Apache Airflow automated python scripts to integrate and transform disparate data sources to a centralized database.
            - Built & maintained the data pipeline with up-time 95 % while ingesting transactional data across 6 data sources using Apache Spark, Nifi & Hive
            - Utilized customer segmentation and look-a-like profiles to generate actionable insights for optimization of campaign and store performance, maximizing return on advertising costs by 22%

     - title: "Data Analyst"
       school:
         name: "Boston Consulting Group"
         url: "https://www.bcg.com/"
       date: "July 2019 - Feb 2020"
       content: |-
          Bengaluru, Karnataka, India
 
            - Developed end-to-end credit risk scorecards with Python programming to predict customer default rate for auto loans which decreased loan approval period from 2 days to 10 seconds.
            - Implemented an advanced personalized recommendation and offer generation tool targeted for the TMT practice area based on a collaborative filtering model in Python.
            - Led supply chain optimization project by developing demand forecasting models to identify supply-demand disruptions to establish optimal product stock replenishment norms, resulting in increased operational efficiency and cost savings.          

     - title: "Software Engineer Intern"
       school:
         name: "ECIL"
         url: "https://www.ecil.co.in/"
       date: "May 2018 - July 2018"
       content: |-
          Hyderabad, Telangana, India
          
            - Developed Human - Emotion Recognition App, to identify and analyze facial expressions of employees at work place.
            - Assessed employees' work interest, productivity, and contribution to the industrial sector, thereby determining the benefits of their involvement.



 # projects
 Projects:
   enable: true
   items:
     - title: Retail Analytics - Product Performance
       content: In the retail supply chain business, the category managers often require a concise overview of product sales performance across their different markets. This helps them differentiate between fast-moving and slow-moving consumer goods, allowing them to optimize their Terms of Trade (ToT) with suppliers.
       image: /images/projects/executive_sales_dashboard.png
       featured:
         name: Tableau Dashboard
         link: https://public.tableau.com/app/profile/katyayani.jandhyala/viz/ExecutiveSalesDashboard_17002804815570/ExecutiveOverview


     - title: Spotify Wrapped
       content: The Spotify Wrapped dashboard delves into a users listening patterns, revealing their most frequently played tracks, genres, top artists, and preferred listening hours. It also takes a retrospective look at their listening habits over the past few years.
       image: /images/projects/spotify_wrapped.png
       featured:
         name: Tableau Dashboard
         link: https://public.tableau.com/app/profile/katyayani.jandhyala/viz/SpotifyWrapped_17005025129330/WebDashboard2


     - title: Airbnb Price Estimator
       content: Airbnb hosts frequently face bottlenecks in determining appropriate pricing for their listings when compared with market trends. Recognizing the significance of listing location, room types, and availability as key determinants,I have developed a regression-based predictive model to estimate the pricing of new listings based on their specific characteristics.
       image: /images/projects/airbnb_host_analysis.png
       featured:
         name: Tableau Dashboard
         link: https://public.tableau.com/app/profile/katyayani.jandhyala/viz/Airbnb_Host_Analysis_Group5_17002870794180/AirbnbHostAnalysis


     - title: Lead Scoring Use Case
       content: Lead scoring is a pivotal metric for assessing leads and has become a standard in contemporary CRM systems. Within this repository, we delve into how the lead scoring strategy helps solve customer conversion problems, exploring the application of various supervised machine learning models.
       image: /images/projects/lead_scoring.png
       featured:
         name: Github Project Link
         link: https://github.com/Katyayani09/Lead-Scoring
 #Contact
 contact:
   enable: true
   content: My inbox is always open. Whether you have a question or just want to say hi, I’ll try my best to get back to you!
   email: katyayani.js@gmail.com
   btnName: Mail me


 footer:
   recentPosts: false
   socialNetworks:
     github: https://github.com/Katyayani09
     linkedin: https://www.linkedin.com/in/katyayanijs/
   # twitter: https://twitter.com
   # facebook: https://facebook.com





