baseURL: "https://katyayani09.github.io"
languageCode: "en-us"
title: "katyayani"
theme: master

Paginate: 3
disqusShortname: Katya
googleAnalytics: G-DWJJVE27WD
canonifyURLs:  true

markup:
  goldmark:
    renderer:
      unsafe: true

#Menus:
  #main:
    #- identifier: blog
      #name: Blog
      #title: Blog posts
      #url: /blogs
      #weight: 1

    #Dropdown menu
    #- identifier: dropdown
      #title: Example dropdown menu
      #name: Dropdown
      #weight: 2
    #- identifier: dropdown1
      #title: example dropdown 1
      #name: example 1
      #url: /#
      #parent: dropdown
      #weight: 1
    #- identifier: dropdown2
      #title: example dropdown 2
      #name: example 2
      #url: /#
      #parent: dropdown
      #weight: 2

params:
  #title: "Hugo Profile"
  #description: Text about my cool site
  # staticPath: ""  # The path to serve the static files from
  #favicon: "/fav.png"

  theme:
    disableThemeToggle: false
    defaultTheme: "light" # dark
    color:  
        secondaryBackgroundColor: "Blue"
    #darkmode:
        #secondaryBackgroundColor: "Blue"

  # font:
  #   fontSize: 1.5rem # default: 1rem
  #   fontWeight: 500 # default: 400
  #   lineHeight: 1 # default: 1.5
  #   textAlign: right # default: left

  # color preference
  # color:
  #     textColor: "black"
  #     secondaryTextColor: 
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  navbar:
      position: absolute
  #   align: mx-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
  #   brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
  #   brandName: "Profile" # Brand name for the brand | default is the title variable

  #   menus:
  #     disableAbout: true
  #     disableExperience: true
  #     disableEducation: true
  #     disableProjects: true
  #     disableAchievements: true
  #     disableContact: true

  # Hero
  hero:
    enable: true
    intro: "Hi there! I'm"
    title: "Katyayani J"
    #subtitle: 
    content: "I'm a passionate business analytics enthusiast on a quest to explore uncharted territories in data science and deliver value-driven solutions across diverse domains. I live in Urbana Champaign, Illinos"
    image: "images/me_.jpg"
    button:
      background - color:
      enable: true
      name: "Resume"
      url: "https://drive.google.com/file/d/1O_tSQAoBPswfecgqsQ5sa8s5BwnBgWss/view?usp=sharing"
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/Katyayani09
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/katyayanijs/
        - icon: fab fa-instagram
          url: https://www.instagram.com/cholechaawal/
      #customIcons:
        #- icon: /fav.png
        #  url: "https://example.com"

  # About
  about:
    enable: true
    title: "I'm open to work immediately."
    image: "/images/tempImageuVymn1_adobe_express.jpeg"
    content: |-
      Additionally, I am currently working as a Teaching Asisstant at University of Illinois Urbana-Champaign, US
      I am an accomplished data engineer with core competency in designing scalable data architectures and implementing efficient ETL processes for large-scale data pipelines, with domain expertise in retail, supply chain, finance, and telecom industries. 
      I have a strong interest in the the intersection of Technology and Business.

     
    skills:
      enable: true
      title: "Skills:"
      items:
        - "Python, R, SQL, Git, Sci-Kit Learn, MLops, AWS, Redis, Postgresql, Apache hadoop, Apache hive Apache Airflow, Apache Spark, Docker, Kubernetes"
        - "Mentorship, Multi-Cultural Fluency, Team Player, Leadership"

  # Experience
  experience:
    enable: true
    items:      
      - job: "Project Intern, Business Practicum"
        company: "Wolters Kluwer"
        companyUrl: "https://www.wolterskluwer.com/"
        date: "Jan 2023 - May 2023"
        info:
          enable: true
          content: "Location: Champaign, Illinois, United States "
        featuredLink:
          enable: false
          url: "https://www.wolterskluwer.com/"
        content: |-
          Champaign, Illinois, United States 
            - Performed customer segmentation of large data sets using entity resolution recommendations system for anomaly detection, optimizing accuracy by deep learning with Pytorch, Keras and TensorFlow
            - Implemented A/B optimization to compare parallelized processing reducing processing time from 2 hours to 50 minutes
            - Leveraged advanced topic modeling techniques such as Latent Dirichlet Allocation (LDA) and guided LDA to effectively analyze copious amounts of ticketing data from multiple global regions
            - Employed unsupervised machine learning algorithms to accurately classify tickets into their respective issue categories, streamlining the issue resolution process for faster turnaround times
      
      - job: "Senior Data Analyst"
        company: "Ganit Inc"
        companyUrl: "https://www.ganitinc.com/"
        date: "Jan 2020 - Aug 2021"
        info:
          enable: true
          content: "Location: Chennai, Tamil Nadu, India"
        featuredLink:
          enable: false
          url: "https://www.ganitinc.com/"
        info:
          content:
        content: |-
          Chennai, Tamil Nadu, India
            - Developed and deployed Tableau dashboards to track 30+ KPIs for hypermarkets, providing a data-driven platform for business stakeholders and, also, reduced weekly man hours by 66.7%
            - Led the migration from SQL Server to Redshift using Amazon Athena & S3, resulting in an annual cost savings of $14,000& increased performance of 23%
            - Spearheaded the design and implementation of a Jenkins-based CI/CD pipeline for a prominent retail e-commerce client. This innovative solution seamlessly integrated Docker and Kubernetes, delivering remarkable results—a remarkable 40% reduction in deployment time while fortifying security through robust Identity and Access Management (IAM) policies
            - Led a data integration initiative, extracting and standardizing data from 40+ sources into a unified format via the creation of 5 ETL packages using Oracle PL/SQL. Further, developed database applications, using Packages, Functions, Procedures, Triggers in PL/SQL, with a strong background in troubleshooting, and performance tuning.
            - Developed data pipelines through Apache Airflow automated python scripts to integrate and transform disparate data sources to a centralized database.
            - Built & maintained the data pipeline with up-time 95 % while ingesting transactional data across 6 data sources using Apache Spark, Nifi & Hive
            - Utilized customer segmentation and look-a-like profiles to generate actionable insights for optimization of campaign and store performance, maximizing return on advertising costs by 22%

      - job: "Data Analyst"
        company: "Boston Consulting Group"
        companyUrl: "https://www.bcg.com/"
        date: "Oct 2019 - Jan 2020"
        info:
          enable: true
          content: "Location: Bengaluru, Karnataka, India"
        featuredLink:
          enable: false
          url: "https://www.bcg.com/"
        info:
          content:
        content: |-
          Bengaluru, Karnataka, India
            - Developed end-to-end credit risk scorecards with Python programming to predict customer default rate for auto loans which decreased loan approval period from 2 days to 10 seconds.
            - Implemented an advanced personalized recommendation and offer generation tool targeted for the TMT practice area based on a collaborative filtering model in Python.
            - Led supply chain optimization project by developing demand forecasting models to identify supply-demand disruptions to establish optimal product stock replenishment norms, resulting in increased operational efficiency and cost savings.          

      - job: "Software Engineer Intern"
        company: "ECIL"
        companyUrl: "https://www.ecil.co.in/"
        date: "June 2017 - July 2017"
        info:
          enable: true
          content: "Location: Hyderabad, Telangana, India  "
        featuredLink:
          enable: false
          url: "https://www.ecil.co.in/"
        content: |-
          Hyderabad, Telangana, India
            - Developed Human - Emotion Recognition App, to identify and analyze facial expressions of employees at work place.
            - Assessed employees' work interest, productivity, and contribution to the industrial sector, thereby determining the benefits of their involvement.

  # Education
  education:
    enable: true
    # index: true
    items:
      - title: "MS, Business Analytics"
        school:
          name: "Gies College of Business - University of Illinois Urbana-Champaign"
          url: "https://giesbusiness.illinois.edu/"
        date: "Aug 2022 - May 2023"
        GPA: "3.9 out of 4.0"
        content: |-
            - currently a Teaching Assistant for Big Data at the Gies College of Business - University of Illinois Urbana-Champaign
            - Course Work: Revenue Management, Business Practicum, Enterprise Database Management, Big Data Infrastructures, Supply Chain Analytics, Data Science and Analytics, Project Management, Marketing Analytics, Data Storytelling, Big Data Analytics in Finance.

      - title: "BTech. Computer Science and Engineering"
        school:
          name: "Vellore Institute of Technology(VIT), Vellore"
          url: "https://vit.ac.in/"
        date: "Jul 2015 - Jul 2019"
        GPA: "3.4 out of 4.0"
        content: |- 
          - Graduated from Computer Science and Engineering (SCOPE) at VIT University, Vellore with a CGPA of 3.4. During my studies
          - Course Work: Machine Learning, Artificial Intelligence, Data Mining, Cyber Security, Network and Communication, Image Processing, Content Based Image and Video Retrieval, Parallel and Distributed Computing,Green and Energy Aware Computing, Theory of Computation, Object Oriented Programming in Python, Software Engineering, Sensors and Instrumentation, Internet of Things, Database Management Systems, Mass Media and Society, Principles of Marketing, Lean-Startup Management, Calculus, Statistics and Probability, and Linear Algebra.

          Extracurricular Activities
            - Board Member at IEEE-TEMS Chapter 
            - Innovations Intern at TIFAC-CORE in Automotive Infotronics 
            - Qualified for Silver & Bronze Echelon at Hack4Cause - a 24 hours Hackathon at the 16th International Conference on Science,Engineering and Technology (ICSET 2018)

  #featuredLink:
  #enable: true
  #name: "My academic record"
  #url: "https://example.com"

  # projects
  projects:
    enable: true
    items:
      - title: Colorizer - Deep Learning
        content: A Deep learning based application that converts a Black and White (Grayscale) Image/Video into a Colour video without human guidance.
        image: /images/projects/Colorization3.png
        featured:
          name: Click here to know more!
          link: https://docs.google.com/presentation/d/193X-n0sXoFbMR9dD7rxJxwM8n_GpOwNQ/edit?usp=sharing&ouid=116008293600462184270&rtpof=true&sd=true
        # badges:
        #   - "Hugo"
        #   - "Bootstrap"
        #   - "Javascript"
        links:
          #- icon: fa fa-envelope
          #  url: mailto:?subject=Hugo%20Profile%20Template&body=Check%20it%20out:%20https%3a%2f%2fhugo-profile.netlify.app%2fblog%2fmarkdown-syntax%2f
          - icon: fab fa-bar-chart
            url: https://github.com/Katyayani09/Deep-Learning/blob/main/Gray%20Scale%20Image%20Colorization%20using%20Auto%20Encoders%20(Fruits%20Data%20Set).ipynb
          # - icon: fab fa-twitter
          #  url: https://twitter.com/intent/tweet?text=Check+it+out:&url=https%3A%2F%2Fgithub.com%2Fgurusabarish%2Fhugo-profile

      - title: Elon Musk Dogecoin Tweet Analysis - NLP
        content: Analyzed the sentiments around Elon's tweets about Dogecoin and impact of his tweets on the price of Doge coin.
        image: /images/projects/doge4.jpeg
        featured:
          name: Click here to know more!
          link: https://github.com/Katyayani09/Elon_Musk-Doge-Tweet_Analysis/blob/main/Facts_derived_from_the_study.pdf
        # badges:
        #   - "Django"
        #   - "Bootstrap"
        links:
          - icon: fab fa-bar-chart
            url: https://github.com/Katyayani09/Elon_Musk-Doge-Tweet_Analysis

      - title: Marketing Insights - Statistics
        content: Digging through data and finding significant insights to advertise better products to customers of different backgrounds.
        image: /images/projects/advert1.jpeg
        featured:
          name: Click here to know more!
          link: https://github.com/Katyayani09/statistics/blob/main/Project.pdf
        # badges:
        #   - "Hugo"
        #   - "Bootstrap"
        #   - "Javascript"
        links:
          - icon: fab fa-bar-chart
            url: https://github.com/Katyayani09/statistics/blob/main/Project.pdf

  #Contact
  contact:
    enable: true
    content: My inbox is always open. Whether you have a question or just want to say hi, I’ll try my best to get back to you!
    email: katyayani.js@gmail.com
    btnName: Mail me

  footer:
    recentPosts: false
    socialNetworks:
      github: https://github.com/Katyayani09
      linkedin: https://www.linkedin.com/in/katyayanijs/
    # twitter: https://twitter.com
      instagram: https://www.instagram.com/cholechaawal/
    # facebook: https://facebook.com
